/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PtGanttChart {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLPtGanttChartElement extends Components.PtGanttChart, HTMLStencilElement {
    }
    var HTMLPtGanttChartElement: {
        prototype: HTMLPtGanttChartElement;
        new (): HTMLPtGanttChartElement;
    };
    interface HTMLElementTagNameMap {
        "pt-gantt-chart": HTMLPtGanttChartElement;
    }
}
declare namespace LocalJSX {
    interface PtGanttChart {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "pt-gantt-chart": PtGanttChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pt-gantt-chart": LocalJSX.PtGanttChart & JSXBase.HTMLAttributes<HTMLPtGanttChartElement>;
        }
    }
}
